export interface Color {
  name: string;
  src: string;
}

export const colorOptions = {
  lam: [
    { name: "American Walnut", src: "/colours/lam/American Walnut SF.png" },
    {
      name: "Arizona Black Walnut Veneer",
      src: "/colours/lam/Arizona Black Walnut Veneer.PNG",
    },
    { name: "Autumn Leaf", src: "/colours/lam/Autumn Leaf SF.png" },
    { name: "Baliness Scuro Oak", src: "/colours/lam/Baliness Scuro Oak.png" },
    { name: "Black pearl", src: "/colours/lam/Black pearl SF.png" },
    { name: "Black", src: "/colours/lam/Black SF.png" },
    { name: "Brazilian Walnut", src: "/colours/lam/Brazilian Walnut.png" },
    { name: "Canadian Walnut", src: "/colours/lam/Canadian Walnut.png" },
    {
      name: "Canterbury Kaos Oak",
      src: "/colours/lam/Canterbury Kaos Oak.png",
    },
    { name: "Chamois Tropical", src: "/colours/lam/Chamois Tropical.png" },
    { name: "Clammy Maple", src: "/colours/lam/Clammy Maple.png" },
    { name: "Cobble Stone", src: "/colours/lam/Cobble Stone SF.png" },
    { name: "Hazel Cambric", src: "/colours/lam/Hazel Cambric.png" },
    { name: "Helsinki Pike Oak", src: "/colours/lam/Helsinki Pike Oak SF.png" },
    {
      name: "Hooked Holz Acacia",
      src: "/colours/lam/Hooked Holz Acacia SF HRZ.png",
    },
    { name: "Irish Cream", src: "/colours/lam/Irish Cream SF.png" },
    { name: "Ivory Frost Glossy", src: "/colours/lam/Ivory Frost Glossy.png" },
    { name: "Laurel Oak", src: "/colours/lam/Laurel Oak.png" },
    { name: "Meadow Kaos Oak", src: "/colours/lam/Meadow Kaos Oak.png" },
    { name: "Mellow Oak", src: "/colours/lam/Mellow Oak.png" },
    { name: "Platinum", src: "/colours/lam/Platinum SF.png" },
    {
      name: "Silver metalic high glossy",
      src: "/colours/lam/Silver metalic high glossy.png",
    },
    { name: "Slate", src: "/colours/lam/Slate SF.png" },
    { name: "White Cambric", src: "/colours/lam/White Cambric.png" },
    { name: "Winter Sea", src: "/colours/lam/Winter Sea SF.PNG" },
  ],
  pu: [
    { name: "Abyss", src: "/colours/pu/ABYSS.PNG" },
    { name: "Alabaster", src: "/colours/pu/ALABASTER.PNG" },
    { name: "Almond Bisque", src: "/colours/pu/ALMOND BISQUE.PNG" },
    { name: "Anthracite", src: "/colours/pu/ANTHRACITE.PNG" },
    { name: "Apricot Blush", src: "/colours/pu/APRICOT BLUSH.PNG" },
    { name: "Aqua Fresh", src: "/colours/pu/AQUA FRESH.PNG" },
    { name: "Arsenic Grey", src: "/colours/pu/ARSENIC GREY.PNG" },
    { name: "Ashen Aura", src: "/colours/pu/ASHEN AURA.PNG" },
    { name: "Azure Grey", src: "/colours/pu/AZURE GREY.PNG" },
    { name: "Beige Rage", src: "/colours/pu/BEIGE RAGE.PNG" },
    { name: "Beige Whiff", src: "/colours/pu/BEIGE WHIFF.PNG" },
    { name: "Black Shellac", src: "/colours/pu/BLACK SHELLAC.PNG" },
    { name: "Blue Vista", src: "/colours/pu/BLUE VISTA.PNG" },
    { name: "Cadet Blue", src: "/colours/pu/CADET BLUE.PNG" },
    { name: "Cappuccino", src: "/colours/pu/CAPPUCCINO.PNG" },
    { name: "Carbonite Matt", src: "/colours/pu/CARBONITE MATT.PNG" },
    { name: "Chamois Matt", src: "/colours/pu/CHAMOIS MATT.PNG" },
    { name: "Charcoal Smudge", src: "/colours/pu/CHARCOAL SMUDGE.PNG" },
    { name: "Chelsea Grey", src: "/colours/pu/CHELSEA GREY.PNG" },
    { name: "Cinnamon", src: "/colours/pu/CINNAMON.PNG" },
    { name: "Cliffside", src: "/colours/pu/CLIFFSIDE.PNG" },
    { name: "Cloud Grey", src: "/colours/pu/CLOUD GREY.PNG" },
    { name: "Cocoa Lava", src: "/colours/pu/COCOA LAVA.PNG" },
    { name: "Cocoa Vibe", src: "/colours/pu/COCOA VIBE.PNG" },
    { name: "Cotton Candy", src: "/colours/pu/COTTON CANDY.PNG" },
    { name: "Cream Caress", src: "/colours/pu/CREAM CARESS.PNG" },
    { name: "Creamette", src: "/colours/pu/CREAMETTE.PNG" },
    { name: "Crisp", src: "/colours/pu/CRISP.PNG" },
    { name: "Deep Mine", src: "/colours/pu/DEEP MINE.PNG" },
    { name: "Deep Tangerine", src: "/colours/pu/DEEP TANGERINE.PNG" },
    { name: "Denim Dusk", src: "/colours/pu/DENIM DUSK.PNG" },
    { name: "Desert Mode", src: "/colours/pu/DESERT MODE.PNG" },
    { name: "Dorian Grey", src: "/colours/pu/DORIAN GREY.PNG" },
    { name: "Dusk Blue", src: "/colours/pu/DUSK BLUE.PNG" },
    { name: "Emerald Green", src: "/colours/pu/EMERALD GREEN.PNG" },
    { name: "Estuarin Matt", src: "/colours/pu/ESTUARIN MATT.PNG" },
    { name: "Ethereal", src: "/colours/pu/ETHEREAL.PNG" },
    { name: "Fern Haven", src: "/colours/pu/FERN HAVEN.PNG" },
    { name: "Foamy White", src: "/colours/pu/FOAMY WHITE.PNG" },
    { name: "Futura Grey Matt", src: "/colours/pu/FUTURA GREY MATT.PNG" },
    { name: "Glacier Grey", src: "/colours/pu/GLACIER GREY.PNG" },
    { name: "Green Lagoon Matt", src: "/colours/pu/GREEN LAGOON MATT.PNG" },
    { name: "Green Lush", src: "/colours/pu/GREEN LUSH.PNG" },
    { name: "Grey Drift", src: "/colours/pu/GREY DRIFT.PNG" },
    { name: "Grigio Ferrous", src: "/colours/pu/GRIGIO FERROUS.PNG" },
    { name: "Grigio Moda", src: "/colours/pu/GRIGIO MODA.PNG" },
    { name: "Gris Anchora", src: "/colours/pu/GRIS ANCHORA.PNG" },
    { name: "Gris Glacia", src: "/colours/pu/GRIS GLACIA.PNG" },
    { name: "Honey Cream", src: "/colours/pu/HONEY CREAM.PNG" },
    { name: "Imperial Green Matt", src: "/colours/pu/IMPERIAL GREEN MATT.PNG" },
    { name: "Indigo Craft", src: "/colours/pu/INDIGO CRAFT.PNG" },
    { name: "Indigo Slate", src: "/colours/pu/INDIGO SLATE.PNG" },
    { name: "Irish Hush", src: "/colours/pu/IRISH HUSH.PNG" },
    { name: "Ivory Matt", src: "/colours/pu/IVORY MATT.PNG" },
    { name: "Lichen Grey", src: "/colours/pu/LICHEN GREY.PNG" },
    { name: "Light Celery", src: "/colours/pu/LIGHT CELERY.PNG" },
    { name: "Lyric Blue", src: "/colours/pu/LYRIC BLUE.PNG" },
    { name: "Mauve Dessert", src: "/colours/pu/MAUVE DESSERT.PNG" },
    { name: "Meadow Brook", src: "/colours/pu/MEADOW BROOK.PNG" },
    { name: "Misty Gray", src: "/colours/pu/MISTY GRAY.PNG" },
    { name: "Moody Maroon", src: "/colours/pu/MOODY MAROON.PNG" },
    { name: "Nebula Grey", src: "/colours/pu/NEBULA GREY.PNG" },
    { name: "Nimbus Grey", src: "/colours/pu/NIMBUS GREY.PNG" },
    { name: "Nova", src: "/colours/pu/NOVA.PNG" },
    { name: "Oliva Matt", src: "/colours/pu/OLIVA MATT.PNG" },
    { name: "Olive Cedar", src: "/colours/pu/OLIVE CEDAR.PNG" },
    { name: "Olive Gaze", src: "/colours/pu/OLIVE GAZE.PNG" },
    { name: "Olive Miro", src: "/colours/pu/OLIVE MIRO.PNG" },
    { name: "Opaline Green", src: "/colours/pu/OPALINE GREEN.PNG" },
    { name: "Oyster Grey", src: "/colours/pu/OYSTER GREY.PNG" },
    { name: "Pale Moss", src: "/colours/pu/PALE MOSS.PNG" },
    { name: "Pebble Sand", src: "/colours/pu/PEBBLE SAND.PNG" },
    { name: "Piomba", src: "/colours/pu/PIOMBA.PNG" },
    { name: "Pomice", src: "/colours/pu/POMICE.PNG" },
    { name: "Rosso Rustic", src: "/colours/pu/ROSSO RUSTIC.PNG" },
    { name: "Sable Brown", src: "/colours/pu/SABLE BROWN.PNG" },
    { name: "Sage Enigma", src: "/colours/pu/SAGE ENIGMA.PNG" },
    { name: "Sage Garden", src: "/colours/pu/SAGE GARDEN.PNG" },
    { name: "Sage Zen", src: "/colours/pu/SAGE ZEN.PNG" },
    { name: "Sand Dune", src: "/colours/pu/SAND DUNE.PNG" },
    { name: "Sedona Red", src: "/colours/pu/SEDONA RED.PNG" },
    { name: "Serenity", src: "/colours/pu/SERENITY.PNG" },
    { name: "Sienna Red", src: "/colours/pu/SIENNA RED.PNG" },
    { name: "Smoke Blue", src: "/colours/pu/SMOKE BLUE.PNG" },
    { name: "Taupe Essence", src: "/colours/pu/TAUPE ESSENCE.PNG" },
    { name: "Taupe Whisper", src: "/colours/pu/TAUPE WHISPER.PNG" },
    { name: "Thyme Green", src: "/colours/pu/THYME GREEN.PNG" },
    { name: "Tortora Matt", src: "/colours/pu/TORTORA MATT.PNG" },
    { name: "Umbertone", src: "/colours/pu/UMBERTONE.PNG" },
    { name: "Urban Grey", src: "/colours/pu/URBAN GREY.PNG" },
    { name: "Vale Mist", src: "/colours/pu/VALE MIST.PNG" },
    { name: "Verde Whisper", src: "/colours/pu/VERDE WHISPER.PNG" },
    { name: "Vintage Rose", src: "/colours/pu/VINTAGE ROSE.PNG" },
    { name: "White", src: "/colours/pu/WHITE.PNG" },
  ],
};
